Java/Leetcode-Reverse-Nodes-in-k-Group.java

Added Leetcode Hard problem-Reverse Nodes in K Group

---

Trees/Same Tree.cpp

Kindly add my piece of code to your repository it will be a great help for me in the hacktoberfest. This piece of code is about checking whether the given trees are identical or not. 
Thanking You in advance.

check whether trees are identical

---

String/Z-Algorithm.cpp

Z algorithm has time complexity of o(m+n) for searching one string into another

Added Z-Algorithm

---

CPP/Sudoku Solver

Here is the leetcode solution of Sudoku solver one of the hard questions of Leetcode

C++ Sudoku solver

---

CPP/Rotate Image

Add this in repo of Rotate Image a common interview question.

Rotate Image Leetcode

---

CPP/sorting/Cyclic Sort

Added the Code for Cyclic Sort in C++

organized CPP code and added new folder wise code

---

CPP/array-2d/find_3rd_max.cpp
CPP/array-2d/find_max.cpp
CPP/array-2d/find_triplet.cpp
CPP/array-2d/rodate_array.cpp

added more basic problem solutions related to an array

basic operations in an array

---

CPP/Problems/Leetcode-07-reverseInteger.cpp
CPP/Problems/Leetcode-38-countAndSay.cpp

Solved Leetcode Problem number 38 (Count and Say).

Created Leetcode-38-countAndSay.cpp

---

Python/Nestedlist.py

This PR adds a solution to the challenge to find the runners' up score  and print in alphabetical order

Added Nested List in python 

---

CPP/graph_tree/Dijkstra_Algorithm.cpp

Added Dijkstra’s Algorithm for calculating Shortest distance in graph_tree sub-folder of CPP folder.

added Dijkstra’s Algorithm

---

Java/QuickSort_Array.java

I have written the code in Java to sort the Array using QuickSort Sorting Technique.

Sorting Algorithm Technique

---

CPP/Problems/Leetcode-219.cpp

Created Leetcode-219.cpp

---

CPP/graph_tree/Bellman-Ford-Algorithm.cpp

Added Bellman-Ford Algorithm for Shortest Distance with Negative Edge in graph_tree subfolder of CPP folder.

added Bellman-Ford Algorithm

---

CPP/sorting/bucketsort.cpp

It is mainly used when input is uniformly distributed over a range. It sort a large set of floating point numbers and are uniformly distributed across the range.

Added Bucket Sort Algo

---

String/BalanceBrackets.cpp

Check whether brackets are balanced or not using stack implementation

---

CPP/Problems/Find First and Last Position of Element in Sorted Array.cpp
CPP/Problems/Leetcode 35- Search Insert Position.cpp
CPP/Problems/Leetcode 66 -Plus One.cpp
CPP/Problems/check-if-it-is-a-straight-line.cpp
CPP/Problems/kids-with-te-greatest-number-of-candies.cpp
CPP/Problems/merge-sorted-arrays.cpp
CPP/Problems/move-zeroes.cpp
CPP/Problems/queries-on-number-of-points-inside-circle.cpp

The questions are from Leetcode problems that I am solving—interested in adding more of these.

Added Leetcode problems in the cpp folder for the Problems Folder

---

Java/LeetCode-Best-Poker-Hand.java
Java/LeetCode-Plus-One.java

- Added solution of LeetCode problems (easy)
Links of the following Problems:
- https://leetcode.com/problems/best-poker-hand/
- https://leetcode.com/problems/plus-one/

Added Leetcode Problems (easy)

---

CPP/graph_tree/Kruskal-Algo.cpp
CPP/graph_tree/Prim-Algo.cpp
CPP/graph_tree/dfs.cpp

Added Minimum Spanning Tree – MST using Prim’s Algo in graph_tree subfolder of CPP folder.

added prim's algo

---

Java/even-odd-number-using-bitwise-and.java

to check if a number is even or odd using bitwise and

---

Trees/treeDuplicate.java

The program finds out if there is any duplicate value in the tree, in Java.

Commit treeDuplicate.java

---

Dynamic Programming/Rod-Cutting.cpp

added Rod Cutting DP problem in Dynamic Programming folder.

added Rod Cutting DP problem

---

CPP/Problems/mergeLinedList/Namanjain6152.md
CPP/Problems/two-sum.cpp

new way to merge two sorted linked list

Merge sorted linked list

---

Python/DIVIDE THE LIST INTO THREE STACKS.py

PYTHON CODE TO DIVIDE THE LIST INTI THREE STACKS

DIVIDE THE LIST INTI THREE STACKS

---

CPP/Problems/Leetcode-1470-Shuffle the Array.cpp

Added problem 1470 to shuffle an Array

Leetcode-1470-Shuffle the Array

---

Python/biggest-odd.py
Python/odd-even.py
Python/string_range.py

**This PR add more python programs.** 
1. _Odd-even.py_ -  Program that finds the difference between the largest even number in the list and the smallest odd number in the list
2. _biggest-odd.py_ - Program that that takes a string of numbers and returns the biggest odd number in the list.
3. _string_range.py_ - Program that that takes a single number and returns a string of its range( Separated by periods)

Added More python programs in the Python folder 

---

Dynamic Programming/Matching - Bitmasking dp

A technique to solve problems related to Bitmasking dp.

Matching - Bitmasking DP

---

Java/Sorting Techniques/Insertion_Sort

Insertion sort a way to sort a list of elements in O(n^2) time complexity

Insertion Sort

---

Java/Next Greater Element II

Here we find the next greater element in a circular array by using a stack in a optimized way

LeetCode Next Greater Element ll

---

Dynamic Programming/fibonacci Num.cpp

Fibonacci Number program with different approaches for logic building

Create fibonacci Num.cpp

---

CPP/Problems/MinimizeTheHeight.cpp
CPP/Problems/findTheDuplicateNumber.cpp
CPP/Problems/minimumNumberOfJump.cpp

Added solution for 3 problems- 
1. Find the duplicate number
2. minimize number of jumps 
3. minimize the heights

added program for duplicate number, minimum jump, minimize height

---

Java/Searching-Algorithms/LinearSearch.java
Java/Sorting Techniques/Bubble_Sort.java

Added code for bubble sort in Java

Added code for bubble sort in java

---

CPP/MatrixTraversing.cpp

It will print numbers of an array spirally.

Code to spirally traverse a matrix

---

CPP/k_th_arrays.cpp

Find element which is k-th position of final sorted array

K-th element of two sorted Arrays

---

Python/quick-sort.py

This PR add a recursive quicksort implementation written in python

Add python quicksort implementation

---

Java/spiralmatrix.java

spiral matrix

---

Python/factorial.py

The product of an integer and all the integers below it is known as factorial
e.g. factorial four ( 4! ) is equal to 24.
`n! = n*(n-1)*...*1`

Added Factorial program in Python

---

Java/Leetcode-Sum of All Subset XOR Totals.java

Added Leetcode - 1863-Sum of All Subset XOR Totals-Solution
Kindly review it and merge this PR under hacktoberfest-accepted label

Leetcode -1863-Solution

---

Java/Leetcode-N-th Tribonacci Number.java

Added Solution of  Leetcode - 1137- N-th Tribonacci Number
Kindly review it and merge this PR under hacktoberfest-accepted label

Leetcode-1137-Solution

---

Dynamic Programming/Egg_Drop.cpp
Dynamic Programming/Longest_Increasing_Subsequence.cpp

Added following DP problems to the list:
- Longest Increasing Subsequence (LIS)
- Egg Dropping Problem

Added few DP Problems Solution

---

Java/Searching-Algorithms/BinarySearch.java

Added BinarySearch source code.

Added BinarySearch code file.

---

Java/Pattern-Questions/AP1.java
Java/Pattern-Questions/AP2.java
Java/Pattern-Questions/ChristmasTree.java
Java/Pattern-Questions/Question1.java
Java/Pattern-Questions/Question10.java
Java/Pattern-Questions/Question11.java
Java/Pattern-Questions/Question12.java
Java/Pattern-Questions/Question13.java
Java/Pattern-Questions/Question14.java
Java/Pattern-Questions/Question2.java
Java/Pattern-Questions/Question3.java
Java/Pattern-Questions/Question4.java
Java/Pattern-Questions/Question5.java
Java/Pattern-Questions/Question6.java
Java/Pattern-Questions/Question7.java
Java/Pattern-Questions/Question8.java
Java/Pattern-Questions/Question9.java

Added 10-15 pattern questions in Java which will helps the folks to build their fundamentals.

Added Pattern Questions in Java

---

Dynamic Programming/5_Check_Palindrome.cpp

Contains 2 methods to check whether a string is palindrome or not

Checking Palindrome String

---

CPP/Problems/kth-largest-element-in-an-array.cpp
CPP/Problems/maximum-subarray.cpp

Issue #78 
Adding solution of 
1. Kth Largest Element in an Array
2. Maximum Subarray

Adding Leetcode problems

---

Java/Searching-Algorithms/BinarySearch.java

Added missing code in file BinarySearch.java .

Binary Search in java

---

Java/Array/Reverse.java
Java/Searching-Algorithms/BinarySearch.java

Added java code for reversing an array using 2 pointer method .

Reversing an array using 2 pointer method

---

Java/Searching-Algorithms/BinarySearch.java
Java/Sorting Techniques/SelectionSort.java

added java code for selection sort algorithm

Selection Sort JAVA

---

CPP/graph_tree/articulation_Point.cpp
Dynamic Programming/minimumPointsToReachDestination.cpp

Added a new dp question and clear solution to that question in memoization and tabulation methods.

added dp sum

---

CPP/Problems/Leetcode-24-Swap Nodes In Pairs.cpp

Leetcode-24-Swap Nodes In Pairs(Linked list)

Leetcode-24-Swapping Nodes In Pairs

---

CPP/Problems/leetcode-347-Top-K-Frequent-Elements.cpp

Adding Top k most frequent elements leetcode problem

---

CPP/Tries/autoComplete.cpp

Added Solution for Tries Autocomplete Search

added tries autocomplete solution

---

Dynamic Programming/uniquePath.cpp

Kindly review it and please merge this PR under the hacktoberfest-accepted label.

added unique Path problem on Dp

---

Java/MatrixMulication

Java code for matrix multiplication.

Added Matrix Mulitplication.Java

---

Java/Leetcode-LetterTilePossibilities.java

Added Solution of Leetcode - 1079 - Letter Tile Possibilities
Kindly review it and merge this PR under hacktoberfest-accepted.

Leetcode - 1079 - Solution

---

Java/Leetcode-IteratorforCombination.java

Added solution of Leetcode - 1286 - Iterator for Combination
Kindly review it and merge this PR under hacktoberfest-accepted label

Leetcode - 1286 - Solution

---

Python/remove_i_character_from_string.py

remove ith character from string

---

CPP/Problems/Leetcode-120-Traingle.cpp
CPP/Problems/Leetcode-19-RemoveNthNodeFromEndOfList.cpp
CPP/Problems/Leetcode-198-HouseRobber.cpp
CPP/Problems/Leetcode-39-CombinationSum.cpp
CPP/Problems/Leetcode-40-CombinationSumII.cpp
CPP/Problems/Leetcode-77-Combinations.cpp
CPP/Problems/Leetcode-784-LetterCasePermutation.cpp

#78 Added 7 CPP solutions to leetcode problems (Medium level)
#hacktoberfest

Added 7 leetcode medium questions

---

Python/Cyclic_Sort.py

Added Cyclic Sorting Method using Python

Added Cyclic Sort.py

---

Java/Leetcode_LRUCache.java

Optimal solution for important interview problem Least Recently Used Cache. 
This solution is written in Java. 
Time Complexity of get() : O(1)  
Time Complexity of put() : O(1)  
Please add HacktoberFest labels.

Create Leetcode_LRUCache.java for HacktoberFest2022

---

Java/Linked List/LeetCode_61_Rotate_List.java

Added Java solution of Leetcode 61. Rotate List medium question with comments.

Added Leetcode Rotate List java solution

---

CPP/recursion/N_Queens/N_Queens.cpp
CPP/recursion/N_Queens/README.md

Signed-off-by: pkm774 <mprabhat774@gmail.com>

CPP/recursion: Add N-Queens problem solution

---

Python/bellman_ford.py

Added python implementation of bellmand ford

---

Java/Sorting Techniques/Cyclic_Sort.java

Added Cyclic Sort using Java. Cyclic sort is a sorting algorithm which sort integers [1 to n] in O(n) time complexity and O(1) space complexity.

Added Cyclic_Sort in Java

---

Dynamic Programming/number_of_dice_rolls_with_target_sum.cpp
Python/decodeWays.py

1) Oct 1st : Number of dice rolls with target sum 
2) Oct 2nd : Decode ways 
Added these problems, please review it and let me know if you want me to add any more comments or change anything

Added two daily leetcode challenge problems

---

Java/Sorting Techniques/CountSort.java

This algorithm is able to do sorting in Linear time.

Added Count Sort Algorithm

---

Dynamic Programming/uniquePaths2.cpp

Kindly review it and please merge this PR under the hacktoberfest-accepted label.

Added unique Paths 2 on DP

---

Python/Sorting-Techniques/InsertionSort.py

Added InsertionSort.py . Insertion sort is a simple sorting algorithm that builds the final sorted array one item at a time.

Added InsertionSort.py

---

Java/String/Optimal Partition of String

Optimal Partition of String

---

Soduko-solver.java

Here's an solution to the opened issue
Please add hacktoberfest tag

Soduko-solver.java

---

Python/5 recusrion problems.py
Python/add two linked list.py
Python/find pairs.py
Python/permutation.py

recursion problems

---

CPP/recursion/Say Digits

Given a number N, output a string that say's the number itself. For example, N=312
Then the output should be "three one two".

Create Say Digits

---

CPP/sliding-window/Sliding Window Maximum.cpp

Please approve my pr and add hacktoberfest label on it.

Create Sliding Window Maximum.cpp

---

CPP/recursion/Predict Winner of Circular Game

There are n friends that are playing a game. The friends are sitting in a circle and are numbered from 1 to n in clockwise order. More formally, moving clockwise from the ith friend brings you to the (i+1)th friend for 1 <= i < n, and moving clockwise from the nth friend brings you to the 1st friend.
The rules of the game are as follows:
Start at the 1st friend.
Count the next k friends in the clockwise direction including the friend you started at. The counting wraps around the circle and may count some friends more than once. The last friend you counted leaves the circle and loses the game. If there is still more than one friend in the circle, go back to step 2 starting from the friend immediately clockwise of the friend who just lost and repeat. Else, the last friend in the circle wins …

Create Predict Winner of Circular Game

---

Maths/nge1_496.cpp
Maths/nge2_503.cpp
Maths/nge3_556.cpp
Maths/reordered_power_of_2_869.cpp
Maths/xor_sum_of_all_pairs_and_1835.cpp

Added solutions for following problems:
- [Next Greater Element 1](https://leetcode.com/problems/next-greater-element-i/)
- [Next Greater Element 2](https://leetcode.com/problems/next-greater-element-ii/)
- [Next Greater Element 3](https://leetcode.com/problems/next-greater-element-iii/)
- [XOR sum of all pairs Bitwise AND](https://leetcode.com/problems/find-xor-sum-of-all-pairs-bitwise-and/)
- [Reordered power of 2](https://leetcode.com/problems/reordered-power-of-2/)

Added solutions to selected leetcode problems

---

CPP/LINKED LIST/SOME LEET CODE QUESTIONS/Design_a_Text_Editor.cpp

Added Design A Text Editor Problem. Leetcode-2296

Addition to Linked List - Leetcode Problems

---

Java/String/BackspaceStringCompare.java

This is two pointer solution for this problem but can be solved using STACK.

Added backspace string compare solution

---

Python/same_tree.py

I have added the solution with description for leetcode question number 100 "same tree". please merge it with the main repo with "hacktoberfest" tag.

added same tree q. no. 100

---

56-LEETCODE-SOLUTION-Merge-interval.java

Leetcode solution merge interval.java

---

Python/Largest of the three numbers.py

Mark it as Hacktoberfest/Hacktoberfest-accepted

Largest of the three numbers - Python(Basic)

---

Python/animation_of_colorful_spiral_pattern.py

This program code display Animation of Colorful Spiral Pattern with the help of turtle and time library.

added code for Animation Colorful Spiral Pattern

---

Python/floyd_warshall.py

Implemented Floyd Warshall Algorithm

---

Dynamic Programming/burstBalloons.cpp

Kindly review it and please merge this PR under the hacktoberfest-accepted label.

added burst balloons problem on DP

---

CPP/structures/stack using linked list.cpp

Algorithm for implementing stack using linked list.
Please add this algo to your repository under hacktoberfest tag. 
Hope it will helpful to you 😊

Stack Using Linked List

---

Python/clumsy_factorial.py

Added a Python script on Clumsy factorial.

Clumsy Factorial

---

Java/Majority_Element.java

In this, I have solved one of the most frequently asked questions by many good IT Companies.
Find the Majority Element of Leetcode.

Find Majority Elements

---

Trees/children sum property

the thread is of children sum property. In the children sum property, we have to see for every node of that tree, the value of that node is equal to the sum of the value of all of its children.

Create children sum property

---

Dynamic Programming/Longest Increasing Subsequence.cpp

this is my code for Longest Increasing Subsequence

Create Longest Increasing Subsequence.cpp

---

Dynamic Programming/Minimum Time to Make Rope Colorful.cpp

this is my code for Minimum Time to Make Rope Colorful

Create Minimum Time to Make Rope Colorful.cpp

---

Dynamic Programming/Circular Palindromes.cpp

Hackerrank Problem - Circular Palindromes
Level - Hard
Lang - c++

Added circular palindrome cpp 

---

CSharp/Programming Skills 1/count-odd-numbers-in-an-interval-range-1523.cs

Added C# solution for #1523 Count Odd Numbers in an Interval Range

Added count-odd-numbers-in-an-interval-range-1523

---

Linked List/Linked_list.cpp

Added algorithms to create, display, insert, delete, search and count nodes in a linked list.

---

Python script to display ip address and host name.py

Python script to display ip address and host name. Please add hacktoberfest tags.

Create python script to display ip address

---

Java/BinarySearchSQRT.java

Find square root of a number using binary search.

SQRT_using_BinarySearch

---

CPP/recursion/Rat in a Maze

Consider a rat placed at (0, 0) in a square matrix of order N * N. It has to reach the destination at (N - 1, N - 1). Find all possible paths that the rat can take to reach from source to destination. The directions in which the rat can move are 'U'(up), 'D'(down), 'L' (left), 'R' (right). Value 0 at a cell in the matrix represents that it is blocked and rat cannot move to it while value 1 at a cell in the matrix represents that rat can be travel through it. Note: In a path, no cell can be visited more than one time. If the source cell is 0, the rat cannot move to any other cell. Moreover, we have to find all possible routes that the rat can take to reach the bottom-right square.

Create Rat in a Maze

---

CPP/BFS GRAPH ALGO/BFS-GRAPH-ALGO.cpp

changed the directory and applying for new PR.
please add hacktoberfest tags

create BFS-GRAPH-ALGO USING C++

---

String/reverseWordinString.cpp

Problem Name : Reverse Word In String

---

CPP/recursion/Phone Keypad Problem

Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.
A mapping of digits to letters (just like on the telephone buttons) is given below.  Note :1 does not map to any letters.
For example,
digits = "23" then the outputs will be in form of a vector of strings like -> ["ad","ae","af","bd","be","bf","cd","ce","cf"]

Create Phone Keypad Problem

---

ZigZag Conversion

Python solution of ZigZagConversion

zig Zag conversion.py

---

Java/MinimumTimeToColorRope.java

I have tried to use the Greedy Approach to Solve One of the commonly asked questions by many Top Companies.
Also do consider and mark this contribution under the HacktoberFest2022 label.

Minimum Time Taken To Make the Rope Colorful.

---

CPP/Leetcode/33. Search in Rotated Sorted Array/README.md
CPP/Leetcode/33. Search in Rotated Sorted Array/Search in Rotated Sorted Array.cpp

Ques - 33. Search in Rotated Sorted Array
Level - Medium
Lang - cpp
Please merge it under `hactoberfest`

Added Leetcode Problem with solution

---

CPP/arrays/leetcode-problems/Substring with Concatenation of All Words.cpp

lang - cpp
level - hard
Please merge it under `hacktoberfest`

Substring with Concatenation leetcode problem

---

Hashtable/Check if Binary String Has at Most One Segment of Ones.cpp

**Check if Binary String Has at Most One Segment of Ones.** 
here's the solution of it 
please add hacktoberfest tags.

Binary String Has at Most One Segment of Ones.cpp

---

CPP/graph_tree/Floyd Warshall.cpp
CPP/graph_tree/Kosaraju Algorithm.cpp

Added Kosaraju and Floyd Warshall Algorithm in CPP

---

Matrix/MatrixTranspose.cpp

Created folder for matrix problems and added code for transpose of a given matrix in C++

Added Matrix Transpose in C++

---

Python/Searching-Algorithms/Jump_search.py

Time Complexity : O(√n) 
Auxiliary Space : O(1)
Important points: 
1.Works only with sorted arrays.
2.The optimal size of a block to be jumped is (√ n). This makes the time complexity of Jump Search O(√ n). 
3.The time complexity of Jump Search is between Linear Search ((O(n)) and Binary Search (O(Log n)). 
4.Binary Search is better than Jump Search, but Jump Search has the advantage that we traverse back only once (Binary Search may require up to O(Log n) jumps, consider a situation where the element to be searched is the smallest element or just bigger than the smallest). So, in a system where binary search is costly, we use Jump Search.

Added jump-search in python

---

Leetcode-solutions/Binary-search/Best Time to Buy and Sell Stock.cpp

Leetcode solution : Best Time to Buy and Sell Stock

Create  Best Time to Buy and Sell Stock.cpp

---

disjoint set - Copy/code.cpp
disjoint set - Copy/readme.txt

Adding Disjoint set data structure code.
It helps in finding a group, and also for finding all points connected to one another.

Add disjoint_set.cpp

---

Trees/BottomView.cpp

Added bottom view for tree

---

Python/Searching-Algorithms/interpolation_search.py

Time Complexity: O(log2(log2 n)) for the average case, and O(n) for the worst case 
Auxiliary Space Complexity: O(1)

Added interpolation search in python

---

CPP/sorting/Cocktail Sort.cpp

Added the code of Cocktail Sort which is a variation of bubble sort, pls check it and merge.

Create Cocktail Sort.cpp

---

Python/CheckForPrime.py

Prime Number: A number that is divisible only by itself and 1 
(e.g. 2, 3, 5, 7, 11).

Added Prime checker in python

---

Hashtable/Removing an element from a Hashtable

This program removes  an element from a HashTable.

Removal of an element in a Hashtable

---

Java/String/Optimal Partition of String
Java/leetcode_Valid Parentheses

Valid Parentheses

---

Python/linked_list_cycle_2.py

Add a solution to the famous LeetCode problem `Linked List Cycle 2`.

Linked List Cycle 2

---

graph/code1.cpp
graph/code10.cpp
graph/code11.cpp
graph/code12.cpp
graph/code13.cpp
graph/code14.cpp
graph/code15.cpp
graph/code16.cpp
graph/code17.cpp
graph/code18.cpp
graph/code19.cpp
graph/code2.cpp
graph/code20.cpp
graph/code3.cpp
graph/code4.cpp
graph/code5.cpp
graph/code6.cpp
graph/code7.cpp
graph/code8.cpp
graph/code9.cpp
graph/readme.txt

This file contains all algorithms of graph.
In readme it is defined which code is for which algorithm...

Add graph.cpp

---

Sudoku-Solver.cpp

Hi @codemistic, I have added the sudoku solver code. Please merge it.

 Sudoku-Solver

---

LeetCode Solutions/lowestCommonAncestor.txt

created solution for a leetcode problem

lowestCommonAncestor.txt added

---

LeetCode Solutions/minDepth.txt

created solution for a leetcode problem

minDepth.txt added

---

LeetCode Solutions/rightSideView.txt

created solution for a leetcode problem

rightSideView.txt added

---

LeetCode Solutions/sortedArrayToBST.txt

created solution for a leetcode problem

sortedArrayToBST.txt added

---

basic dsa/1 Armstrong Number

Create 1 Armstrong Number

---

Trees/binary-tree-zigzag-level-order-traversal.cpp
Trees/flatten-binary-tree-to-linked-list.cpp

Merge this to your repository with hacktoberfest label

Zigzag level order traversal

---

Leetcode-solutions/Binary-search/Longest Substring Without Repeating Characters

Given a string s, find the length of the longest substring without repeating characters.
The idea is checking whenever we find any letter which is repeating we can find previous position and find the difference
we can check "repeating" by maintain hash functions like map

Long_Substr_w/o_Repeat_Char

---

CPP/pandigital_numbers/code.cpp
CPP/pandigital_numbers/readme.txt

A number is said to be pandigital if it contains each of the digits from 0 to 9 (and whose leading digit must be nonzero).
code is of Problem statement: https://projecteuler.net/problem=43

Add pandigital_num.cpp

---

Trees/LCA.cpp

Finding Least Common Ancestor using Binary Lifting Technique.

Least Common Ancestor

---

Python/Dynamic_Programming/CountMinSteps.py
Python/Dynamic_Programming/CountMinSteps_Iterative.py
Python/Dynamic_Programming/Introduction.py
Python/Dynamic_Programming/Longest_consecutive_subsequence.py
Python/Dynamic_Programming/Longest_subsequence_iterative.py

There were no DP question in the python data structure folder , so i have added DP section and question , introduction about Dynamic Programming.

Dynamic Programming has been added in the Python language.

---

CSharp/Programming Skills 1/average-salary-excluding-the-minimum-and-maximum-salary-1491.cs

New C# solution for Average Salary Excluding the Minimum and Maximum Salary.
All test cases passed.
Runtime: 126ms
Memory Usage: 37.2 MB

Added Average Salary Solution for 1491

---

CPP/Greedy_algorithm.cpp
CPP/Sieve of Eratosthenes.cpp

Adding Sieve of Eratosthenes algorithm in cpp

Adding Sieve of Eratosthenes.cpp

---

Prime or not

Create Prime or not

---

CPP/Problems/Leetcode-1254-NumberOfClosedIslands.cpp
CPP/Problems/Leetcode-733-FloodFill.cpp
CPP/Trees/LowestCommonAncestor.cpp
CPP/Trees/TargetSum.cpp

This PR contains two code files for Binary Trees `LCA` and `Target Sum` under CPP / Trees, and two Leetcode solutions regarding graphs i.e. `Flood Fill` and `Number of Closed Islands`, under CPP / Problems.

Added leetcode codes for two Trees and Graph problems

---

Java/Stack/BalancedBrackets.java
Java/Stack/InfixToPrefix.java

The Balanced Brackets program can also be used for the pre-existing InfixToPostfix converter to evade invalid expressions.

Add : Balanced Brackets and InfixToPrefix program in Java

---

CPP/Problems/COINS - Bytelandian gold coins

I have added solution to a problem on SPOJ.
Problem Link: https://www.spoj.com/problems/COINS/
Please accept it and mark it as Hacktoberfest accepted.

Create COINS - Bytelandian gold coins

---

Dynamic Programming/minimumPathFallingSum.java
Dynamic Programming/minimumPathSumDP.java
Dynamic Programming/triangle.java
graph/cycleDetectionInDirectedGraph.java
graph/cycledetectionInUndirectedGraph.java

DP and Graph easy implementation JAVA

---

Trees/addOneRowToTree.cpp

I wrote the code on today's LC challenge in C++ solved using DFS approach

Added a code on binary trees in C++

---

Java/Leetcode/1614. Maximum Nesting Depth of the Parentheses
Java/Leetcode/198. House Robber

1614. Maximum Nesting Depth of the Parentheses

---

CPP/searching/binary_search_in_rotated_array.cpp

Added Binary Search for a Rotated array

Added Binary Search in Rotated array

---

Python/passwordGenerator.py

A password generator that takes desired length as input and gives a random and secure password. 
Kindly add the `hacktober` topic and merge and add  `hacktober-accepted` if it is approved.
Thanks!

Added random pass gen and resolved issue #615

---

Java/Linked List/LinkedList.java

Added java code for implementing a Linked List from scratch using Java.

Added code for Implementing Linked List using Java

---

Arrays/4.MedianofTwoSortedArray.cpp

Pushkar Roy  Arrays/4.MedianofTwoSortedArray.cpp

---

Arrays/32_Operations_on_arrays.c

an all in one c program for operations on arrays like, traaversing, sorting, searching, adding, deleting, etc.
please merge with hacktoberfest label
(ignore error messages, they are due to the backward compatibility of c++ with c language, the code works just fine)
Closes #464

added file for operations on arrays in c language

---

CPP/Tries/implementTrie.cpp

Implement_Trie

---

Arrays/32_Binary_Search_2D_Arrays.cpp

In this PR, I have added the code for Binary Search on 2D arrays in C++.
Screenshot is attached below for reference:
Please review and merge this.
Thank you!

Binary Search in 2D Arrays (C++)

---

Trees/Leetcode-116. Populating Next Right Pointers in Each Node.cpp
Trees/Leetcode-222. Count Complete Tree Nodes.cpp
Trees/Leetcode-226. Invert Binary Tree.cpp
Trees/Leetcode-230. Kth Smallest Element in a BST.cpp
Trees/Leetcode-623. Add One Row to Tree.cpp

Added  solutions for binary tree

Leetcode Binary Tree Solutions

---

Python/Calculator.py

- Improved functionality
- Added more operations
- Added more comments for readability
- Fixed typos

Improve Calculator.py

---

AhoCorasick.java

Aho-Corasick Algorithm
The Aho-Corasick algorithm efficiently searches for multiple patterns in a given text simultaneously. Using a trie to store patterns and failure links for fast backtracking, it achieves linear time complexity (
𝑂(𝑛+𝑚+𝑧)
O(n+m+z)) where 
𝑛
n is the text length, 
𝑚
m is the total keyword length, and 
𝑧
z is the number of matches.
This implementation is ideal for applications like intrusion detection, spam filtering, and bioinformatics, providing concise and modular code for easy integration.

 Java file for Aho-Corasick searching algorithm
